[package]
name = "wayfinder-tap"
version = "0.1.0"
edition = "2024"

[dependencies]
wayfinder.workspace = true

tracing-subscriber.workspace = true
tracing.workspace = true
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true
tun-rs = { version = "2", features = ["async"] }
etherparse.workspace = true
embedded-io-adapters.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
libc = "0.2.186"
serde_yaml = "0.9.34"
futures.workspace = true
zerocopy.workspace = true
