variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  CI_REGISTRY_IMAGE: registry.haganah.net
  CI_REGISTRY_IMAGE_TAG: "$CI_REGISTRY_IMAGE/rust-ci:latest"
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_PROTECTED == "true"'
default:
  cache:
    key: "$CI_COMMIT_REF_SLUG" # Use a unique key per branch for better isolation
    paths:
      - "$CARGO_HOME" # Cache the CARGO_HOME directory
      - "target/" # Cache the project's target directory
stages:
  - lint
  - build
  - test
  - deploy
lint:rust:
  stage: lint
  image: rustlang/rust:nightly
  script:
    - rustup component add rustfmt
    - cargo fmt
lint:nix:
  stage: lint
  image: nixos/nix
  script:
    - nix --extra-experimental-features "nix-command flakes" flake check
lint:mr-title:
  stage: lint
  image:
    name: commitlint/commitlint
    entrypoint:
      - ""
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "$CI_MERGE_REQUEST_TITLE" | commitlint
lint-done:
  stage: lint
  needs:
    - lint:rust
    - lint:nix
    - job: lint:mr-title
      optional: true
  script:
    - echo "done"
build:
  stage: build
  image: rustlang/rust:nightly
  needs:
    - lint-done
  script:
    - rustup component add clippy
    - cargo build
    - cargo clippy
test:build-image:
  stage: test
  image: docker:24.0.5 # Standard docker CLI image
  tags:
    - docker
  services:
    - docker:24.0.5-dind # Docker-in-Docker service
  script:
    # 1. Pull the existing image to use as a local cache layer source
    - docker pull $CI_REGISTRY_IMAGE_TAG || true
    # 2. Build using the pulled image as a cache reference
    - docker build -f containers/testenv.Dockerfile --cache-from $CI_REGISTRY_IMAGE_TAG -t $CI_REGISTRY_IMAGE_TAG .
    # 3. Push the newly evaluated/built image back to the registry
    - docker push $CI_REGISTRY_IMAGE_TAG
test:run:
  stage: test
  image: $CI_REGISTRY_IMAGE_TAG
  needs:
    - test:build-image
    - build
  script:
    - cargo llvm-cov nextest --profile ci --workspace --cobertura --output-path coverage.xml
  artifacts:
    reports:
      coverage_report:
        path: coverage.xml
        coverage_format: cobertura
deploy-dev:
  stage: deploy
  needs:
    - test:run
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: dev
deploy-prod:
  stage: deploy
  needs:
    - test:run
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
