[package]
name = "wayfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
interfaces.workspace = true
zerocopy.workspace = true
batman.workspace = true
anyhow.workspace = true
pretty-hex.workspace = true

[dev-dependencies]
tracing-test = "0.2.6"
pretty-hex.workspace = true
