[package]
name = "rylr998"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
embedded-io-async.workspace = true
heapless.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio-serial = "5.4"
anyhow = "1.0.102"
tracing-subscriber.workspace = true
tokio.workspace = true
embedded-io-adapters.workspace = true
