[package]
name = "ieee802154"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
interfaces.workspace = true
tracing = { version = "0.1.44", default-features = false }
wayfinder-link-utils = { path = "../wayfinder-link-utils" }
zerocopy = { version = "0.8.48", features = ["derive"] }
