[package]
name = "interfaces"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
zerocopy = { version = "0.8.48", features = ["derive"] }
embedded-io-async.workspace = true
heapless.workspace = true
core = { version = "1.0", package = "rustc-std-workspace-core", optional = true }
etherparse.workspace = true

[dev-dependencies]
tokio.workspace = true
embedded-io-adapters.workspace = true
