[package]
name = "ieee802154-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.ieee802154]
path = ".."

[dependencies.interfaces]
path = "../../interfaces"

# Use independent workspace for fuzzers
[workspace]
members = ["."]

[[bin]]
name = "accept_fragment"
path = "fuzz_targets/accept_fragment.rs"
test = false
doc = false
bench = false
