[package]
name = "wayfinder-tui"
version = "0.1.0"
edition = "2021"

[lib]
name = "wayfinder_tui"
path = "src/lib.rs"

[[bin]]
name = "wayfinder-tui"
path = "src/main.rs"

[dependencies]
wayfinder-protos.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
anyhow.workspace = true
clap.workspace = true
prost = { version = "0.13", features = ["std"] }
bytes = "1"
ratatui = "0.29"

[dev-dependencies]
wayfinder-server.workspace = true
tokio.workspace = true
anyhow.workspace = true
