[package]
name = "wayfinder-tui"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
name = "wayfinder_tui"
path = "src/lib.rs"

[[bin]]
name = "wayfinder-tui"
path = "src/main.rs"

[dependencies]
wayfinder-protos.workspace = true
wayfinder-client.workspace = true
wayfinder-auth.workspace = true
tokio.workspace = true
anyhow.workspace = true
clap = { workspace = true, features = ["env"] }
serde.workspace = true
serde_json.workspace = true
ratatui = "0.29"
