//! The server functions the browser calls.
//!
//! This is the whole of the browser's access to the node. Each function's body
//! is compiled only into the server build; the wasm build gets a stub that
//! POSTs to it. So `wayfinder-client`, the mesh identity and the node
//! connection all stay server-side by construction rather than by convention.
//!
//! Every function here is a thin wrapper: the work lives in [`crate::snapshot`]
//! and in [`wayfinder_client`], where it can be tested without the server-function
//! machinery in the way.

use leptos::prelude::*;

use crate::enroll::EnrollmentOutcome;
use crate::enroll::ProviderTarget;
use crate::snapshot::NodeSnapshot;

/// Reach the node connection the axum layer put in context.
///
/// Present on every request the server routes (see `main.rs`), so its absence
/// is a wiring bug rather than a runtime condition — reported as a server error
/// rather than panicking, since a panic here would take down the request
/// handler with a far less informative message.
#[cfg(feature = "ssr")]
fn connection() -> Result<std::sync::Arc<crate::conn::NodeConnection>, ServerFnError> {
    use_context::<std::sync::Arc<crate::conn::NodeConnection>>().ok_or_else(|| {
        ServerFnError::new("node connection missing from request context (server wiring bug)")
    })
}

/// Poll the node for one snapshot, resuming the log stream at `since_seq`.
///
/// Pass `0` for a first poll; afterwards pass the `logs.next_seq` from the
/// previous snapshot so each record is read exactly once.
// `#[server]` turns the argument list into a request struct, whose fields carry
// no docs of their own. Scoped to this one function rather than crate-wide,
// matching how `wayfinder-protos` quarantines the same lint over its prost
// bindings, so a genuinely undocumented item elsewhere in this file still fails
// the build. `allow` rather than `expect`: the lint fires inside the macro
// expansion, which expectation tracking does not attribute back to this span.
// `endpoint` is set explicitly on every server function here. Left to itself the
// macro derives a name-mangled path with a hash in it, which changes whenever
// the function is renamed — fine for a browser that fetches the generated stub,
// but it makes the HTTP surface unreadable in a log or a `curl`.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = FetchSnapshot, prefix = "/api", endpoint = "snapshot")]
pub async fn fetch_snapshot(since_seq: u64) -> Result<NodeSnapshot, ServerFnError> {
    let conn = connection()?;
    crate::snapshot::build_snapshot(&conn, since_seq)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// The address or port the dashboard is pointed at, for the header.
///
/// Read once at startup rather than carried on every snapshot: it cannot change
/// while the process runs, and a label that never changes has no business
/// costing bytes on a once-a-second poll.
#[server(name = NodeLabel, prefix = "/api", endpoint = "node_label")]
pub async fn node_label() -> Result<String, ServerFnError> {
    Ok(connection()?.label())
}

/// Which participation gate a [`set_link_gate`] call flips.
///
/// A closed enum rather than a field name string, so an unknown gate is a
/// compile error here and a decode error at the boundary, never a silently
/// ignored request.
#[derive(Clone, Copy, PartialEq, Eq, Debug, serde::Serialize, serde::Deserialize)]
pub enum Gate {
    /// Send OGMs (own and re-flooded) onto the link.
    TxOgm,
    /// Accept inbound OGMs on the link and learn routes from them.
    RxOgm,
    /// Send data-plane traffic onto the link.
    TxData,
    /// Accept inbound data-plane traffic on the link.
    RxData,
}

impl Gate {
    /// The label shown beside the gate's switch.
    ///
    /// Plain language rather than the wire field name: this dashboard is read by
    /// people who have not read the protocol.
    pub fn label(self) -> &'static str {
        match self {
            Gate::TxOgm => "Send OGMs",
            Gate::RxOgm => "Receive OGMs",
            Gate::TxData => "Send data",
            Gate::RxData => "Receive data",
        }
    }

    /// What flipping this gate off actually does, for the switch's tooltip.
    pub fn help(self) -> &'static str {
        match self {
            Gate::TxOgm => {
                "Stop announcing routes on this link. Other nodes stop routing through it."
            }
            Gate::RxOgm => "Stop learning routes from this link.",
            Gate::TxData => "Stop sending traffic on this link.",
            Gate::RxData => "Stop accepting traffic from this link.",
        }
    }
}

/// Open or close one participation gate on one interface.
///
/// Applied immediately with no confirmation: one gate is low-stakes and
/// trivially reversible, unlike the Security tab's actions. The change is
/// in-memory on the node and does not survive its restart.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetLinkGate, prefix = "/api", endpoint = "set_link_gate")]
pub async fn set_link_gate(iface_idx: u32, gate: Gate, value: bool) -> Result<(), ServerFnError> {
    use wayfinder_protos::wayfinder::v1alpha::LinkFeatures;

    let mut features = LinkFeatures {
        iface_idx,
        ..Default::default()
    };
    match gate {
        Gate::TxOgm => features.tx_ogm = Some(value),
        Gate::RxOgm => features.rx_ogm = Some(value),
        Gate::TxData => features.tx_data = Some(value),
        Gate::RxData => features.rx_data = Some(value),
    }

    connection()?
        .run(async |client| client.set_link_features(features).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Approve a pending certificate request, admitting the node to the mesh.
///
/// Provider-only: a node that is not a certificate authority answers with an
/// error. `node_mac` is the raw MAC bytes the request is bound to.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = ApproveCsr, prefix = "/api", endpoint = "approve_csr")]
pub async fn approve_csr(node_mac: Vec<u8>) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.approve_csr(&node_mac).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Deny a pending certificate request.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = DenyCsr, prefix = "/api", endpoint = "deny_csr")]
pub async fn deny_csr(node_mac: Vec<u8>) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.deny_csr(&node_mac).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Revoke a node's membership, so the mesh drops its frames.
///
/// The most consequential action the dashboard offers: the revocation floods
/// the mesh and is not undone by re-approving. Behind a confirmation in the UI
/// for that reason.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = RevokeNode, prefix = "/api", endpoint = "revoke_node")]
pub async fn revoke_node(node_mac: Vec<u8>) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.revoke_node(&node_mac).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Switch the node's fail-closed gate on or off.
///
/// The most consequential setting on the Security tab: turning it on for a node
/// that holds no membership certificate takes that node off the mesh
/// immediately. Behind a confirmation in the UI for that reason.
///
/// Persisted by a node configured with a `runtime_state_path`, so it is still
/// in force after a restart; in memory only on a node without one.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetRequireAuth, prefix = "/api", endpoint = "set_require_auth")]
pub async fn set_require_auth(require: bool) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.set_require_auth(require).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Switch lazy cert distribution on or off.
///
/// A flag-day, wire-incompatible change: a node with this on cannot be
/// understood by an un-upgraded authenticated peer, so the whole mesh has to be
/// upgraded before any node flips it. Behind a confirmation in the UI, which
/// says so.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(
    name = SetLazyCertDistribution,
    prefix = "/api",
    endpoint = "set_lazy_cert_distribution"
)]
pub async fn set_lazy_cert_distribution(enabled: bool) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.set_lazy_cert_distribution(enabled).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// How a [`set_enrollment_policy`] call changes the shared enrollment token.
///
/// A closed enum rather than an `Option<String>` because the two changes it has
/// to express — open enrollment to everyone, and require this secret — are
/// opposites that an empty string would silently conflate.
#[derive(Clone, PartialEq, Eq, Debug, serde::Serialize, serde::Deserialize)]
pub enum TokenChange {
    /// Leave the token exactly as it is.
    Unchanged,
    /// Clear the token: any node that can reach this provider may enroll.
    Clear,
    /// Require this token on a request to join. Never empty.
    Set(String),
}

/// Update the enrollment policy of a provider-mode node: how a node asking to
/// join the mesh is admitted.
///
/// `require_approval` and `cert_ttl_secs` are `None` to leave unchanged, as is
/// [`TokenChange::Unchanged`] for the token. Errors on a node that is not a
/// certificate authority, which has no enrollment policy to change.
///
/// The policy is persisted by the authority alongside the certificates it
/// governs, so it survives a restart.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetEnrollmentPolicy, prefix = "/api", endpoint = "set_enrollment_policy")]
pub async fn set_enrollment_policy(
    require_approval: Option<bool>,
    cert_ttl_secs: Option<u64>,
    token: TokenChange,
) -> Result<(), ServerFnError> {
    use wayfinder_protos::wayfinder::v1alpha::EnrollmentPolicy;
    use wayfinder_protos::wayfinder::v1alpha::enrollment_policy::EnrollmentTokenUpdate;

    // Rejected here as well as by the node: an empty token would gate
    // enrollment on a secret nobody can present, and catching it in the
    // browser's own round trip gives the operator the reason rather than a
    // relayed wire error.
    if matches!(&token, TokenChange::Set(t) if t.is_empty()) {
        return Err(ServerFnError::new(
            "the enrollment token cannot be empty — clear it to open enrollment instead",
        ));
    }

    let policy = EnrollmentPolicy {
        require_approval,
        cert_ttl_secs,
        enrollment_token_update: match token {
            TokenChange::Unchanged => None,
            TokenChange::Clear => Some(EnrollmentTokenUpdate::EnrollmentTokenCleared(true)),
            TokenChange::Set(value) => Some(EnrollmentTokenUpdate::EnrollmentToken(value)),
        },
    };

    connection()?
        .run(async |client| client.set_enrollment_policy(policy).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Ask a provider to admit this node to its mesh, installing the certificate if
/// one is issued.
///
/// The one call here that reaches a node other than this dashboard's own: it
/// opens a short-lived anonymous connection to the provider, submits a CSR for
/// the identity *this* node already holds, and installs what comes back. See
/// [`crate::enroll`] for why it is the node's existing identity being certified
/// rather than a fresh one.
///
/// Call it again with the same arguments to collect a certificate that was held
/// for approval; re-submitting an identical request is how the provider is
/// polled, and does not queue a second one.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = RequestEnrollment, prefix = "/api", endpoint = "request_enrollment")]
pub async fn request_enrollment(
    provider: ProviderTarget,
) -> Result<EnrollmentOutcome, ServerFnError> {
    let conn = connection()?;
    crate::enroll::request(&conn, &provider)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Change the node's runtime log filter, returning the spec now in force.
///
/// The node is the authority on what it accepted: a rejected spec comes back as
/// an error while the previous filter stays in force, so the caller must show
/// what is actually running rather than what was typed.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetLogLevel, prefix = "/api", endpoint = "set_log_level")]
pub async fn set_log_level(directives: String) -> Result<String, ServerFnError> {
    connection()?
        .run(async |client| client.set_log_level(&directives).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}
