//! The server functions the browser calls.
//!
//! This is the whole of the browser's access to the node. Each function's body
//! is compiled only into the server build; the wasm build gets a stub that
//! POSTs to it. So `wayfinder-client`, the mesh identity and the node
//! connection all stay server-side by construction rather than by convention.
//!
//! Every function here is a thin wrapper: the work lives in [`crate::snapshot`]
//! and in [`wayfinder_client`], where it can be tested without the server-function
//! machinery in the way.

use leptos::prelude::*;

use crate::enroll::EnrollmentOutcome;
use crate::enroll::ProviderTarget;
use crate::session::LoginResult;
use crate::session::Viewer;
use crate::snapshot::NodeSnapshot;

/// Reach the credential source the axum layer put in context.
///
/// Present on every request the server routes (see `server.rs`), so its absence
/// is a wiring bug rather than a runtime condition — reported as a server error
/// rather than panicking, since a panic here would take down the request
/// handler with a far less informative message.
#[cfg(feature = "ssr")]
fn access() -> Result<std::sync::Arc<crate::session::Access>, ServerFnError> {
    use_context::<std::sync::Arc<crate::session::Access>>().ok_or_else(|| {
        ServerFnError::new("node access missing from request context (server wiring bug)")
    })
}

/// The session id this request carries, if any.
///
/// Read from the request `leptos_axum` puts in context on both router arms — a
/// server-function call and a server-rendered page alike — so a page knows
/// whether to render the dashboard or the login form without a second round
/// trip.
#[cfg(feature = "ssr")]
fn session_id() -> Option<String> {
    use_context::<axum::http::request::Parts>().and_then(|parts| {
        parts
            .headers
            .get(axum::http::header::COOKIE)
            .and_then(|value| value.to_str().ok())
            .and_then(crate::session::id_from_cookie_header)
            .map(str::to_owned)
    })
}

/// The current time in unix seconds, for session expiry.
#[cfg(feature = "ssr")]
fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_secs())
}

/// Reach the node connection this request is entitled to.
///
/// In static mode that is the process's one connection. In login mode it is the
/// session's own — and its absence is [`crate::session::NEEDS_LOGIN`], which
/// the browser renders as "log in" rather than as a node that has gone away.
#[cfg(feature = "ssr")]
fn connection() -> Result<std::sync::Arc<crate::conn::NodeConnection>, ServerFnError> {
    access()?
        .connection(session_id().as_deref(), now_unix())
        .ok_or_else(|| ServerFnError::new(crate::session::NEEDS_LOGIN))
}

/// Who is looking at the dashboard: static mode, logged out, or a live session.
///
/// The first thing the page asks, and the answer decides whether anything else
/// is rendered at all.
#[server(name = SessionState, prefix = "/api", endpoint = "session")]
pub async fn session_state() -> Result<Viewer, ServerFnError> {
    Ok(access()?.viewer(session_id().as_deref(), now_unix()))
}

/// Exchange a username, password and TOTP code at the provider for a session.
///
/// The exchange happens here, server-side, and the browser receives a cookie
/// naming the session — never the key or the certificate the provider issued.
/// A refusal comes back as [`LoginResult::Denied`] rather than as an error: it
/// is an answer to be rendered, and it carries no detail because the provider
/// gives none.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = Login, prefix = "/api", endpoint = "login")]
pub async fn login(
    username: String,
    password: String,
    totp_code: String,
) -> Result<LoginResult, ServerFnError> {
    use crate::session::Access;
    use crate::session::LoginOutcome;

    let access = access()?;
    let Access::Login(store) = &*access else {
        return Err(ServerFnError::new(
            "this dashboard runs on a static credential and has no login",
        ));
    };

    let outcome = store
        .login(&username, &password, totp_code.trim(), now_unix())
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))?;

    match outcome {
        LoginOutcome::LoggedIn { id, info } => {
            set_cookie(&crate::session::session_cookie(&id, request_is_secure()))?;
            Ok(LoginResult::LoggedIn(info))
        }
        LoginOutcome::Denied => Ok(LoginResult::Denied),
    }
}

/// Sign in with a `.wfauth` credential file instead of a password.
///
/// The offline half of [`login`]: the file already holds a certificate the
/// provider signed, so nothing is asked of the provider — which is the point,
/// since a deployment can be cut off from its certificate authority and still
/// need its dashboard. The node is asked, once, before the session is called
/// real (see [`crate::session::SessionStore::login_with_bundle`]).
///
/// `bundle` is the file's text, read in the browser and sent as-is; the browser
/// does not look inside it, and the parsing, the validity check and the
/// credential all stay on this side.
///
/// Unlike [`login`], a refusal here comes back as an *error with its reason*.
/// There is no account to enumerate — the caller is holding their own file —
/// so the reticence that makes a password refusal say nothing would only cost
/// the reader the one fact that tells them what to do next.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = LoginWithBundle, prefix = "/api", endpoint = "login_bundle")]
pub async fn login_with_bundle(bundle: String) -> Result<LoginResult, ServerFnError> {
    use crate::session::Access;
    use crate::session::LoginOutcome;

    let access = access()?;
    let Access::Login(store) = &*access else {
        return Err(ServerFnError::new(
            "this dashboard runs on a static credential and has no sign-in",
        ));
    };

    let outcome = store
        .login_with_bundle(&bundle, now_unix())
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))?;

    match outcome {
        LoginOutcome::LoggedIn { id, info } => {
            set_cookie(&crate::session::session_cookie(&id, request_is_secure()))?;
            Ok(LoginResult::LoggedIn(info))
        }
        // Not produced by this path — every refusal above is an error carrying
        // its reason — but the outcome type is shared with the password login
        // and this keeps the match honest rather than unreachable.
        LoginOutcome::Denied => Ok(LoginResult::Denied),
    }
}

/// End this browser's session, dropping the connection it authenticated.
#[server(name = Logout, prefix = "/api", endpoint = "logout")]
pub async fn logout() -> Result<(), ServerFnError> {
    use crate::session::Access;

    let access = access()?;
    if let Access::Login(store) = &*access {
        store.end(session_id().as_deref());
    }
    // Cleared unconditionally: a cookie naming a session that no longer exists
    // is harmless but keeps the browser presenting a dead id on every request.
    set_cookie(&crate::session::cleared_cookie(request_is_secure()))
}

/// Whether this request arrived over TLS, deciding the cookie's `Secure`
/// attribute. See `session::request_is_secure`.
#[cfg(feature = "ssr")]
fn request_is_secure() -> bool {
    use_context::<axum::http::request::Parts>()
        .is_some_and(|parts| crate::session::request_is_secure(&parts.headers))
}

/// Attach a `Set-Cookie` header to this server function's response.
#[cfg(feature = "ssr")]
fn set_cookie(value: &str) -> Result<(), ServerFnError> {
    let options = use_context::<leptos_axum::ResponseOptions>().ok_or_else(|| {
        ServerFnError::new("response options missing from request context (server wiring bug)")
    })?;
    let header = axum::http::HeaderValue::from_str(value)
        .map_err(|e| ServerFnError::new(format!("building the session cookie: {e}")))?;
    options.append_header(axum::http::header::SET_COOKIE, header);
    Ok(())
}

/// Poll the node for one snapshot, resuming the log stream at `since_seq`.
///
/// Pass `0` for a first poll; afterwards pass the `logs.next_seq` from the
/// previous snapshot so each record is read exactly once.
// `#[server]` turns the argument list into a request struct, whose fields carry
// no docs of their own. Scoped to this one function rather than crate-wide,
// matching how `wayfinder-protos` quarantines the same lint over its prost
// bindings, so a genuinely undocumented item elsewhere in this file still fails
// the build. `allow` rather than `expect`: the lint fires inside the macro
// expansion, which expectation tracking does not attribute back to this span.
// `endpoint` is set explicitly on every server function here. Left to itself the
// macro derives a name-mangled path with a hash in it, which changes whenever
// the function is renamed — fine for a browser that fetches the generated stub,
// but it makes the HTTP surface unreadable in a log or a `curl`.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = FetchSnapshot, prefix = "/api", endpoint = "snapshot")]
pub async fn fetch_snapshot(since_seq: u64) -> Result<NodeSnapshot, ServerFnError> {
    let conn = connection()?;
    crate::snapshot::build_snapshot(&conn, since_seq)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// The address or port the dashboard is pointed at, for the header.
///
/// Read once at startup rather than carried on every snapshot: it cannot change
/// while the process runs, and a label that never changes has no business
/// costing bytes on a once-a-second poll.
#[server(name = NodeLabel, prefix = "/api", endpoint = "node_label")]
pub async fn node_label() -> Result<String, ServerFnError> {
    // From the access rather than a connection: the label is what the process
    // was pointed at, which is knowable — and worth showing — before anyone has
    // logged in.
    Ok(access()?.label())
}

/// Which participation gate a [`set_link_gate`] call flips.
///
/// A closed enum rather than a field name string, so an unknown gate is a
/// compile error here and a decode error at the boundary, never a silently
/// ignored request.
#[derive(Clone, Copy, PartialEq, Eq, Debug, serde::Serialize, serde::Deserialize)]
pub enum Gate {
    /// Send OGMs (own and re-flooded) onto the link.
    TxOgm,
    /// Accept inbound OGMs on the link and learn routes from them.
    RxOgm,
    /// Send data-plane traffic onto the link.
    TxData,
    /// Accept inbound data-plane traffic on the link.
    RxData,
}

impl Gate {
    /// The label shown beside the gate's switch.
    ///
    /// Plain language rather than the wire field name: this dashboard is read by
    /// people who have not read the protocol.
    pub fn label(self) -> &'static str {
        match self {
            Gate::TxOgm => "Send OGMs",
            Gate::RxOgm => "Receive OGMs",
            Gate::TxData => "Send data",
            Gate::RxData => "Receive data",
        }
    }

    /// What flipping this gate off actually does, for the switch's tooltip.
    pub fn help(self) -> &'static str {
        match self {
            Gate::TxOgm => {
                "Stop announcing routes on this link. Other nodes stop routing through it."
            }
            Gate::RxOgm => "Stop learning routes from this link.",
            Gate::TxData => "Stop sending traffic on this link.",
            Gate::RxData => "Stop accepting traffic from this link.",
        }
    }
}

/// Open or close one participation gate on one interface.
///
/// Applied immediately with no confirmation: one gate is low-stakes and
/// trivially reversible, unlike the Security tab's actions. The change is
/// in-memory on the node and does not survive its restart.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetLinkGate, prefix = "/api", endpoint = "set_link_gate")]
pub async fn set_link_gate(iface_idx: u32, gate: Gate, value: bool) -> Result<(), ServerFnError> {
    use wayfinder_protos::wayfinder::v1alpha::LinkFeatures;

    let mut features = LinkFeatures {
        iface_idx,
        ..Default::default()
    };
    match gate {
        Gate::TxOgm => features.tx_ogm = Some(value),
        Gate::RxOgm => features.rx_ogm = Some(value),
        Gate::TxData => features.tx_data = Some(value),
        Gate::RxData => features.rx_data = Some(value),
    }

    connection()?
        .run(async |client| client.set_link_features(features).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Approve a pending certificate request, admitting the node to the mesh.
///
/// Provider-only: a node that is not a certificate authority answers with an
/// error. `node_mac` is the raw MAC bytes the request is bound to.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = ApproveCsr, prefix = "/api", endpoint = "approve_csr")]
pub async fn approve_csr(node_mac: Vec<u8>) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.approve_csr(&node_mac).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Deny a pending certificate request.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = DenyCsr, prefix = "/api", endpoint = "deny_csr")]
pub async fn deny_csr(node_mac: Vec<u8>) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.deny_csr(&node_mac).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Revoke a node's membership, so the mesh drops its frames.
///
/// The most consequential action the dashboard offers: the revocation floods
/// the mesh and is not undone by re-approving. Behind a confirmation in the UI
/// for that reason.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = RevokeNode, prefix = "/api", endpoint = "revoke_node")]
pub async fn revoke_node(node_mac: Vec<u8>) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.revoke_node(&node_mac).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Switch the node's fail-closed gate on or off.
///
/// The most consequential setting on the Security tab: turning it on for a node
/// that holds no membership certificate takes that node off the mesh
/// immediately. Behind a confirmation in the UI for that reason.
///
/// Persisted by a node configured with a `runtime_state_path`, so it is still
/// in force after a restart; in memory only on a node without one.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetRequireAuth, prefix = "/api", endpoint = "set_require_auth")]
pub async fn set_require_auth(require: bool) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.set_require_auth(require).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Switch lazy cert distribution on or off.
///
/// A flag-day, wire-incompatible change: a node with this on cannot be
/// understood by an un-upgraded authenticated peer, so the whole mesh has to be
/// upgraded before any node flips it. Behind a confirmation in the UI, which
/// says so.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(
    name = SetLazyCertDistribution,
    prefix = "/api",
    endpoint = "set_lazy_cert_distribution"
)]
pub async fn set_lazy_cert_distribution(enabled: bool) -> Result<(), ServerFnError> {
    connection()?
        .run(async |client| client.set_lazy_cert_distribution(enabled).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// How a [`set_enrollment_policy`] call changes the shared enrollment token.
///
/// A closed enum rather than an `Option<String>` because the two changes it has
/// to express — open enrollment to everyone, and require this secret — are
/// opposites that an empty string would silently conflate.
#[derive(Clone, PartialEq, Eq, Debug, serde::Serialize, serde::Deserialize)]
pub enum TokenChange {
    /// Leave the token exactly as it is.
    Unchanged,
    /// Clear the token: any node that can reach this provider may enroll.
    Clear,
    /// Require this token on a request to join. Never empty.
    Set(String),
}

/// Update the enrollment policy of a provider-mode node: how a node asking to
/// join the mesh is admitted.
///
/// `auto_approve` and `cert_ttl_secs` are `None` to leave unchanged, as is
/// [`TokenChange::Unchanged`] for the token. Errors on a node that is not a
/// certificate authority, which has no enrollment policy to change.
///
/// The policy is persisted by the authority alongside the certificates it
/// governs, so it survives a restart.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetEnrollmentPolicy, prefix = "/api", endpoint = "set_enrollment_policy")]
pub async fn set_enrollment_policy(
    auto_approve: Option<bool>,
    cert_ttl_secs: Option<u64>,
    token: TokenChange,
) -> Result<(), ServerFnError> {
    use wayfinder_protos::wayfinder::v1alpha::EnrollmentPolicy;
    use wayfinder_protos::wayfinder::v1alpha::enrollment_policy::EnrollmentTokenUpdate;

    // Rejected here as well as by the node: an empty token would gate
    // enrollment on a secret nobody can present, and catching it in the
    // browser's own round trip gives the operator the reason rather than a
    // relayed wire error.
    if matches!(&token, TokenChange::Set(t) if t.is_empty()) {
        return Err(ServerFnError::new(
            "the enrollment token cannot be empty — clear it to open enrollment instead",
        ));
    }

    let policy = EnrollmentPolicy {
        auto_approve,
        cert_ttl_secs,
        enrollment_token_update: match token {
            TokenChange::Unchanged => None,
            TokenChange::Clear => Some(EnrollmentTokenUpdate::EnrollmentTokenCleared(true)),
            TokenChange::Set(value) => Some(EnrollmentTokenUpdate::EnrollmentToken(value)),
        },
    };

    connection()?
        .run(async |client| client.set_enrollment_policy(policy).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Read the shared enrollment token a provider-mode node is applying, so an
/// operator can hand it to a node that is joining.
///
/// `None` means enrollment is open — no token is required — which is a
/// different answer from an empty one. Errors on a node that is not a
/// certificate authority.
///
/// Deliberately not part of the once-a-second snapshot: this is a secret, and a
/// value that rides every poll is disclosed continuously to everything that
/// touches the snapshot, while one that travels only when an operator clicks is
/// a discrete act the node records in its log.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = RevealEnrollmentToken, prefix = "/api", endpoint = "reveal_enrollment_token")]
pub async fn reveal_enrollment_token() -> Result<Option<String>, ServerFnError> {
    connection()?
        .run(async |client| client.reveal_enrollment_token().await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Ask a provider to admit this node to its mesh, installing the certificate if
/// one is issued.
///
/// The one call here that reaches a node other than this dashboard's own: it
/// opens a short-lived anonymous connection to the provider, submits a CSR for
/// the identity *this* node already holds, and installs what comes back. See
/// [`crate::enroll`] for why it is the node's existing identity being certified
/// rather than a fresh one.
///
/// Call it again with the same arguments to collect a certificate that was held
/// for approval; re-submitting an identical request is how the provider is
/// polled, and does not queue a second one.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = RequestEnrollment, prefix = "/api", endpoint = "request_enrollment")]
pub async fn request_enrollment(
    provider: ProviderTarget,
) -> Result<EnrollmentOutcome, ServerFnError> {
    let conn = connection()?;
    crate::enroll::request(&conn, &provider)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// The user accounts a provider-mode node holds, for the Provider tab.
///
/// Errors on a node that is not a certificate authority, and on a session that
/// is not an administrator's — the roster of who may administer the mesh is not
/// on the read-only tier.
///
/// Deliberately not part of the once-a-second snapshot: this changes when
/// somebody creates an account and at no other time, and a list that rides
/// every poll is a list re-fetched eighty-six thousand times a day to show the
/// same three names.
#[server(name = ListUsers, prefix = "/api", endpoint = "list_users")]
pub async fn list_users()
-> Result<Vec<wayfinder_protos::wayfinder::v1alpha::UserAccount>, ServerFnError> {
    connection()?
        .run(async |client| client.list_users().await)
        .await
        .map(|response| response.users)
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Create a user account on a provider-mode node, returning the `otpauth://`
/// enrolment URI for its second factor (empty when created without one).
///
/// The URI comes back exactly once and is not recoverable afterwards, so the
/// caller must show it to the operator there and then.
///
/// The password crosses two hops: this browser to this server, and this server
/// to the node over authenticated TLS. Neither is stored — the authority keeps
/// only an Argon2id hash — and the second hop requires an administrator's
/// session, which is what makes the first hop's exposure bounded.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = CreateUser, prefix = "/api", endpoint = "create_user")]
pub async fn create_user(
    username: String,
    password: String,
    admin: bool,
    session_ttl_secs: u64,
    no_totp: bool,
) -> Result<String, ServerFnError> {
    // Refused here as well as by the authority, so an obvious mistake reads as
    // itself rather than as a relayed wire error.
    if username.trim().is_empty() {
        return Err(ServerFnError::new("a user name is required"));
    }
    if password.is_empty() {
        return Err(ServerFnError::new("a password is required"));
    }

    connection()?
        .run(async |client| {
            client
                .create_user(username.trim(), &password, admin, session_ttl_secs, no_totp)
                .await
        })
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Remove a user account on a provider-mode node.
///
/// Ends the account's ability to obtain *new* sessions. A session certificate
/// already issued to it keeps working until it expires — including, if the
/// operator removes their own account, the one making this very request.
///
/// The node decides, not this server: it refuses to remove the last account
/// that can still administer the mesh, and that refusal arrives here as an
/// error to show rather than as something to pre-empt.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = RemoveUser, prefix = "/api", endpoint = "remove_user")]
pub async fn remove_user(username: String) -> Result<(), ServerFnError> {
    if username.trim().is_empty() {
        return Err(ServerFnError::new("a user name is required"));
    }

    connection()?
        .run(async |client| client.remove_user(username.trim()).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}

/// Change the node's runtime log filter, returning the spec now in force.
///
/// The node is the authority on what it accepted: a rejected spec comes back as
/// an error while the previous filter stays in force, so the caller must show
/// what is actually running rather than what was typed.
#[allow(missing_docs, reason = "request struct fields generated by #[server]")]
#[server(name = SetLogLevel, prefix = "/api", endpoint = "set_log_level")]
pub async fn set_log_level(directives: String) -> Result<String, ServerFnError> {
    connection()?
        .run(async |client| client.set_log_level(&directives).await)
        .await
        .map_err(|e| ServerFnError::new(format!("{e:#}")))
}
