//! Linker-script plumbing for `esp-hal`'s runtime.
//!
//! `linkall.x` is generated by `esp-hal`'s own build script — it carries this
//! part's memory layout, so unlike the Cortex-M boards there is no `memory.x`
//! here to hand the linker. It has to come *last* on the linker's script list,
//! hence a `rustc-link-arg` emitted from here rather than a `-T` in
//! `.cargo/config.toml`, whose flags are prepended.

fn main() {
    println!("cargo:rustc-link-arg=-Tlinkall.x");
    println!("cargo:rerun-if-changed=build.rs");
}
