[package]
name = "wayfinder-test"
version = "0.1.0"
edition = "2024"

[dependencies]
wayfinder.workspace = true
interfaces.workspace = true

thiserror.workspace = true
zerocopy.workspace = true
embassy-sync.workspace = true
heapless.workspace = true
embedded-io-async.workspace = true
rand = { workspace = true, features = ["std"] }
tokio.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
