#!/usr/bin/env bash
#
# Assemble the wayfndr.dev landing page into a directory Cloudflare Pages can
# upload verbatim.
#
# There is no bundler and no framework: `www/` is already the site. The only
# thing this script does that a `cp -r` would not is pull the logo in from
# `assets/logo/`, which is the repo's single source of truth for the mark
# (assets/logo/README.md and bins/wayfinder-web/src/components/logo.rs are the
# other two consumers). Copying the SVGs into `www/` and committing them would
# make a fourth copy to keep in sync; resolving them at build time cannot drift.
#
# Usage: scripts/build-site.sh [outdir]     (default: dist/site)

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/dist/site}"

rm -rf "$out"
mkdir -p "$out"

cp -R "$root/www/." "$out/"

# The favicon adapts to the viewer's colour scheme, which is why it is a
# separate file from the header mark — see assets/logo/README.md.
cp "$root/assets/logo/wayfinder-icon.svg" "$out/favicon.svg"
cp "$root/assets/logo/wayfinder-mark.svg" "$out/wayfinder-mark.svg"
cp "$root/assets/logo/wayfinder-mark-mono.svg" "$out/wayfinder-mark-mono.svg"

# The simulation lab's results must have been computed from the router this
# tree holds. `just sim-export` stamps www/sim/data/inputs.sha256 with a hash of
# every input that can move a result; if the tree no longer hashes to it, the
# numbers on the page describe an older router, and publishing them would be
# publishing a claim nobody measured. The site workflow regenerates before it
# gets here; locally, re-export (or set SIM_ALLOW_STALE=1 for a throwaway
# preview, which says so loudly).
if [ -d "$root/www/sim/data" ]; then
  want="$("$root/scripts/sim-inputs-hash.sh")"
  have="$(cat "$root/www/sim/data/inputs.sha256" 2>/dev/null || true)"
  if [ "$want" != "$have" ]; then
    if [ "${SIM_ALLOW_STALE:-}" = 1 ]; then
      echo "build-site: WARNING: www/sim/data is stale (inputs changed since the last 'just sim-export'); building anyway because SIM_ALLOW_STALE=1" >&2
    else
      echo "build-site: www/sim/data is stale: the router, simulator or a scenario changed since the last 'just sim-export'." >&2
      echo "build-site: run 'just sim-export' and commit the result (or SIM_ALLOW_STALE=1 for a throwaway preview)." >&2
      exit 1
    fi
  fi
fi

# The simulation lab draws www/sim/data/*.json, but the site's CSP forbids
# fetch (connect-src 'none'), so the results are bundled into one script the
# page loads like any other. The JSON files are published too, as the "raw
# results" downloads each section links to.
if [ -d "$root/www/sim/data" ]; then
  {
    printf '/* Generated by scripts/build-site.sh from www/sim/data/*.json. */\n'
    printf 'window.WF_SIM = ['
    first=1
    for json in "$root"/www/sim/data/*.json; do
      [ -e "$json" ] || continue
      [ "$first" = 1 ] || printf ','
      first=0
      cat "$json"
    done
    printf '];\n'
  } > "$out/sim/data.js"
fi

# og.html is the 1200x630 source for the social preview image, rendered to
# og.png out of band (see www/README.md). It must not be published as a page.
rm -f "$out/og.html"

# Fail loudly rather than shipping a page whose stylesheet 404s.
for required in index.html styles.css mesh.js favicon.svg wayfinder-mark.svg _headers \
  sim/index.html sim/lab.js sim/lab.css sim/data.js; do
  [ -f "$out/$required" ] || { echo "build-site: missing $required in $out" >&2; exit 1; }
done

echo "build-site: $out ($(find "$out" -type f | wc -l | tr -d ' ') files)"
